### ISSUE TITLE
Cannot write the file to /tmp

### ISSUE THREAD

**Issue by michellaporte** [madchap/graylog2-zabbix#3]
Hey,
Ever seen the issue where the .sh script cannot write the json file to /tmp?
- debug '[get_system_lb_status] Executing'
- '[' '!' -z ']'
- jq -r .lb_status /tmp/192.168.32.163-system.json
  jq: /tmp/192.168.32.163-system.json: No such file or directory

Thanks

**Comment by michellaporte** [comment]
NVM
Seen you have a poller data separately in Zabbix

**Comment by madchap** [comment]
Hi,

Yes, otherwise, I'd say that should be simply a file permission issue (i.e. you ran manually as root and the zabbix process cannot overwrite as user zabbix), as /tmp is set with 1777.

Cheers,
fred

**Comment by michellaporte** [comment]
Thanks @madchap . It wasn't perms. I was just trying to run the script manually without Zabbix then saw the poller /25s in Zabbix :)
