### ISSUE TITLE
Unable to run script, jq error

### ISSUE THREAD

**Issue by serge-khor** [madchap/graylog2-zabbix#7]
I installed jq-1.5 on ubuntu. I used the 1.5 release zip file. When I run the script as ROOT:
`bash check_graylog_node -H hostname -a journal_size -p 12900`

I get this error:
`jq: error: Could not open file /tmp/hostname-journal.json: No such file or directory`

Anybody know what could be causing this?

**Comment by madchap** [comment]
Hi,

I am guessing you need to run poll_data() first, as that method will actually generate the needed json files.

Cheers,
fred

**Comment by serge-khor** [comment]
Thanks!
